### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by robson76** [hschaefer123/openui5-nodeserver#1]
Hi,

I followed the steps you suggested, but when I tried to starting server, occured the following syntax error.

C:\openui5-nodeserver>node index.js
C:\openui5-nodeserver\index.js:4
<!DOCTYPE html>
^
SyntaxError: Unexpected token <
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

SDK version 1.28.15 (2015-08-13)

Best regards.
Robson

**Comment by hschaefer123** [comment]
You have the wrong index.js!!!
It should be the node server side from this repo!
